### ISSUE TITLE
windows gui wallet start error : java.lang.IllegalArgumentException: Malformed \uxxxx encoding

### ISSUE THREAD

**Issue by xilongtao** [BuckCoin/buck-gui-wallet-win#3]
OS : win10
When start by buck-wallet.bat it stucked by report this error;
So i start use a text-cli mode.

**Comment by xilongtao** [comment]
And when start use a gui, how to indicate a customized datadir

**Comment by BuckCoin** [comment]
Try this:

(1) Download the latest release of the BUCK GUI wallet
(2) Make sure the BUCK wallet is closed (the program is not running)
(3) Go to Start -> type in the box %appdata%\buck
(4) Delete all files and folders other than the wallet.dat file (DO NOT DELETE THE wallet.dat FILE!!!)
(5) Run file: buck-wallet.bat

This will probably solve your issue.

**Comment by BuckCoin** [comment]
Assuming resolved. Closed.
